'use strict';
const Contract = require('../models').Contract;
const Property = require('../models').Property;

module.exports = {
  up: async (queryInterface, Sequelize) => {
    const contracts = await Contract.findAll({include: [Property] });

    return queryInterface.bulkInsert('Invoices', [{
      isPaid: true,
      invoiceDate: '2021-01-06',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[0].Property.cost,
      invoiceIncome: contracts[0].Property.income,
      contractId: contracts[0].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-02-06',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[0].Property.cost,
      invoiceIncome: contracts[0].Property.income,
      contractId: contracts[0].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-03-06',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[0].Property.cost,
      invoiceIncome: contracts[0].Property.income,
      contractId: contracts[0].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-04-06',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[0].Property.cost,
      invoiceIncome: contracts[0].Property.income,
      contractId: contracts[0].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-05-06',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[0].Property.cost,
      invoiceIncome: contracts[0].Property.income,
      contractId: contracts[0].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-06-06',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[0].Property.cost,
      invoiceIncome: contracts[0].Property.income,
      contractId: contracts[0].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-07-06',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[0].Property.cost,
      invoiceIncome: contracts[0].Property.income,
      contractId: contracts[0].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-08-06',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[0].Property.cost,
      invoiceIncome: contracts[0].Property.income,
      contractId: contracts[0].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-09-06',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[0].Property.cost,
      invoiceIncome: contracts[0].Property.income,
      contractId: contracts[0].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-10-06',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[0].Property.cost,
      invoiceIncome: contracts[0].Property.income,
      contractId: contracts[0].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-11-06',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[0].Property.cost,
      invoiceIncome: contracts[0].Property.income,
      contractId: contracts[0].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-01-04',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[1].Property.cost,
      invoiceIncome: contracts[1].Property.income,
      contractId: contracts[1].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-02-04',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[1].Property.cost,
      invoiceIncome: contracts[1].Property.income,
      contractId: contracts[1].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-03-04',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[1].Property.cost,
      invoiceIncome: contracts[1].Property.income,
      contractId: contracts[1].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-04-04',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[1].Property.cost,
      invoiceIncome: contracts[1].Property.income,
      contractId: contracts[1].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-05-04',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[1].Property.cost,
      invoiceIncome: contracts[1].Property.income,
      contractId: contracts[1].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-04-04',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[1].Property.cost,
      invoiceIncome: contracts[1].Property.income,
      contractId: contracts[1].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-07-04',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[1].Property.cost,
      invoiceIncome: contracts[1].Property.income,
      contractId: contracts[1].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-08-04',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[1].Property.cost,
      invoiceIncome: contracts[1].Property.income,
      contractId: contracts[1].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-09-04',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[1].Property.cost,
      invoiceIncome: contracts[1].Property.income,
      contractId: contracts[1].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-10-04',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[1].Property.cost,
      invoiceIncome: contracts[1].Property.income,
      contractId: contracts[1].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-11-04',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[1].Property.cost,
      invoiceIncome: contracts[1].Property.income,
      contractId: contracts[1].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-01-10',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[2].Property.cost,
      invoiceIncome: contracts[2].Property.income,
      contractId: contracts[2].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-02-10',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[2].Property.cost,
      invoiceIncome: contracts[2].Property.income,
      contractId: contracts[2].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-03-10',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[2].Property.cost,
      invoiceIncome: contracts[2].Property.income,
      contractId: contracts[2].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-10-10',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[2].Property.cost,
      invoiceIncome: contracts[2].Property.income,
      contractId: contracts[2].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-05-10',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[2].Property.cost,
      invoiceIncome: contracts[2].Property.income,
      contractId: contracts[2].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-10-10',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[2].Property.cost,
      invoiceIncome: contracts[2].Property.income,
      contractId: contracts[2].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-07-10',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[2].Property.cost,
      invoiceIncome: contracts[2].Property.income,
      contractId: contracts[2].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-08-10',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[2].Property.cost,
      invoiceIncome: contracts[2].Property.income,
      contractId: contracts[2].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-09-10',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[2].Property.cost,
      invoiceIncome: contracts[2].Property.income,
      contractId: contracts[2].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-10-10',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[2].Property.cost,
      invoiceIncome: contracts[2].Property.income,
      contractId: contracts[2].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      isPaid: true,
      invoiceDate: '2021-11-10',
      description: 'Factura de arriendo',
      status: true,
      invoiceCost: contracts[2].Property.cost,
      invoiceIncome: contracts[2].Property.income,
      contractId: contracts[2].id,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ], {});
  },

  down: async (queryInterface, Sequelize) => {

  },
};
